title: Alauda Build of SonarQube Docs
logoText: Alauda Build of SonarQube Docs
lang: en
api:
  crds:
    - docs/shared/crds/*.yaml
    - docs/shared/crds/*.yml
  openapis:
    - docs/shared/openapis/**/*.json
    - docs/shared/openapis/**/*.yaml
    - docs/shared/openapis/**/*.yml
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml

editRepoBaseUrl: alauda/sonarqube-docs

releaseNotes:
  queryTemplates:
  ## TODO: change the versionMatch for the next releases
    unfixed: | 
      project = <%= project %> and affectedVersion in versionMatch("sonarqube-ce-operator-v2025.1.[0-9]") and filter = 18959 AND ACPAffectVersions in (<%= acpversion %>) AND NOT (ACPFixVersions in (<%= acpversion %>) AND status in (Done, Resolved)) AND (labels not in (安全问题) OR labels is EMPTY) and ReleaseNotesStatus = Publish
    fixed: | 
      project = <%= project %> and affectedVersion in versionMatch("sonarqube-ce-operator-v2025.1.[0-9]") and filter = 16502 AND (resolution not in ("By Design", "Not a Bug", Duplicate, Rejected, "Cannot Reproduce") OR resolution is EMPTY) AND (ACPFixVersions in (<%= acpversion %>) or fixVersion in versionMatch(<%= acpversion %>)) AND status in (Done, Resolved, 已完成) AND (affectedVersion in versionMatch("3.1[0-8]") OR ((issueFunction in linkedIssuesOf("affectedVersion in versionMatch('3.1[0-8]')", clones) OR issueFunction in linkedIssuesOf("affectedVersion in versionMatch('3.1[0-8]')", "is cloned by")))) and ReleaseNotesStatus = Publish

translate:
  # 系统提示语，ejs 模板，传入的参数有 `sourceLang`, `targetLang`, `additionalPrompts`
  # 其中 `sourceLang` 和 `targetLang` 是 `中文` 和 `英文` 两个字符串，
  #     `additionalPrompts` 为 `i18n` 中的 `additionalPrompts` 配置，可能为空
  # 默认的系统提示语如下，可以根据实际情况进行修改
  userPrompt: |
    - 以下术语请保持不要翻译
      * ACP
      * Alauda Build of SonarQube
      * Administrator
      * Marketplace
      * Operator Hub
