title: Alauda Build of SonarQube Docs
logoText: Alauda Build of SonarQube Docs
lang: en
api:
  crds:
    - docs/shared/crds/*.yaml
    - docs/shared/crds/*.yml
  openapis:
    - docs/shared/openapis/**/*.json
    - docs/shared/openapis/**/*.yaml
    - docs/shared/openapis/**/*.yml
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml

editRepoBaseUrl: alauda/sonarqube-docs

releaseNotes:
  queryTemplates:
  ## TODO: change the versionMatch for the next releases
    unfixed: |
      project = <%= project %> AND affectedVersion in ("sonarqube-ce-operator-<%= version %>") AND type = Bug AND status in (Cancelled) AND ReleaseNotesStatus = Publish

    fixed: |
      project = <%= project %> AND fixVersion in ("sonarqube-ce-operator-<%= version %>") AND type = Bug AND status in (Done, Resolved) AND ReleaseNotesStatus = Publish

translate:
  # 系统提示语，ejs 模板，传入的参数有 `sourceLang`, `targetLang`, `additionalPrompts`
  # 其中 `sourceLang` 和 `targetLang` 是 `中文` 和 `英文` 两个字符串，
  #     `additionalPrompts` 为 `i18n` 中的 `additionalPrompts` 配置，可能为空
  # 默认的系统提示语如下，可以根据实际情况进行修改
  userPrompt: |
    - 以下术语请保持不要翻译
      * ACP
      * Alauda Build of SonarQube
      * Administrator
      * Marketplace
      * Operator Hub
